apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos

spec:
  replicas: 2

  selector:
    matchLabels:
      app: pedidos

  template:
    metadata:
      labels:
        app: pedidos

    spec:
      containers:
      - name: pedidos
        image: loja/pedidos:1.0

---
apiVersion: v1
kind: Service

metadata:
  name: pedidos

spec:
  selector:
    app: pedidos

  ports:
    - port: 5000